/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author divsi
 */
public class memberDatabase extends javax.swing.JPanel {

    /**
     * Creates new form memberDatabase
     */
    public memberDatabase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        memberRadio = new javax.swing.JRadioButton();
        supplierRadio = new javax.swing.JRadioButton();
        staffRadio = new javax.swing.JRadioButton();
        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "NIC", "Name", "DOB", "Gender", "Contact", "Address", "Package", "Amount", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 1150, 590));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by Name", "Search by Code", "Search by Enrolled Date", "Search by Package", "Load Activated", "Load Deactivated" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 210, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 250, 30));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 30, 30));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 270, 30));

        buttonGroup1.add(memberRadio);
        memberRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        memberRadio.setText("Member");
        memberRadio.setContentAreaFilled(false);
        memberRadio.setFocusPainted(false);
        memberRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberRadioMouseClicked(evt);
            }
        });
        add(memberRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 30));

        buttonGroup1.add(supplierRadio);
        supplierRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierRadio.setText("Supplier");
        supplierRadio.setContentAreaFilled(false);
        supplierRadio.setFocusPainted(false);
        supplierRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierRadioMouseClicked(evt);
            }
        });
        add(supplierRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 30));

        buttonGroup1.add(staffRadio);
        staffRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffRadio.setText("Staff");
        staffRadio.setContentAreaFilled(false);
        staffRadio.setFocusPainted(false);
        staffRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffRadioMouseClicked(evt);
            }
        });
        add(staffRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, 30));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 0, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Database       ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        jRadioButton1.setText("Show Activated");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void memberRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberRadioMouseClicked
        titleLabel.setText("Member");
    }//GEN-LAST:event_memberRadioMouseClicked

    private void supplierRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierRadioMouseClicked
        titleLabel.setText("Supplier");
    }//GEN-LAST:event_supplierRadioMouseClicked

    private void staffRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffRadioMouseClicked
        titleLabel.setText("Staff");
    }//GEN-LAST:event_staffRadioMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton memberRadio;
    private javax.swing.JRadioButton staffRadio;
    private javax.swing.JRadioButton supplierRadio;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
