/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author nipun
 */
public class SearchRegistration extends javax.swing.JPanel {

    private static SearchRegistration instance;
    /**
     * Creates new form SearchRegistration
     */
    public SearchRegistration() {
        initComponents();
    }


    public static SearchRegistration getInstance() {
        if (instance == null) {
            instance = new SearchRegistration();
        }
        return instance;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        titleBar = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        parentPanel = new javax.swing.JPanel();
        searchStaff = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        searchMember = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1206, 708));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(204, 204, 204));
        titleBar.setFocusable(false);
        titleBar.setPreferredSize(new java.awt.Dimension(1206, 740));
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        titleLabel.setText(".... Registration");
        titleBar.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 230, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Supplier");
        buttonGroup1.add(jButton1);
        titleBar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Member");
        buttonGroup1.add(jButton2);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        titleBar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("Staff");
        buttonGroup1.add(jButton3);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        titleBar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 40));

        add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1206, 40));

        parentPanel.setLayout(new java.awt.CardLayout());

        searchStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nic", "Name", "Gender", "Contact No", "Address", "Payment", "Entroll Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        searchStaff.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1124, 533));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchStaff.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 250, 30));

        searchStaff.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 30));
        searchStaff.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 30, 30));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by Name", "Search by Nic", "Load Activated", "Load Deactivated", "Load All", " " }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        searchStaff.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("View Payments");
        searchStaff.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sort By:");
        searchStaff.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 30));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setText("Alphabetical Order");
        searchStaff.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, 30));

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6.setText("Entroll Date");
        searchStaff.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 30));

        parentPanel.add(searchStaff, "card2");

        searchMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nic", "Name", "Dob", "Gender", "Contact No", "Address", "Entroll Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Dob");
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Gender");
        }

        searchMember.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1124, 533));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchMember.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 250, 30));

        searchMember.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 30));
        searchMember.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 30, 30));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by Name", "Search by Code", "Search by Nic", "Load Activated", "Load Deactivated", "Load All", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        searchMember.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sort By:");
        searchMember.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 30));

        buttonGroup3.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Entroll Date");
        searchMember.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 30));

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Alphabetical Order");
        searchMember.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("View Payments");
        searchMember.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("View Package");
        searchMember.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, 30));

        parentPanel.add(searchMember, "card2");

        add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1206, 668));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  parentPanel.removeAll();
        parentPanel.add(searchMember);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          parentPanel.removeAll();
        parentPanel.add(searchStaff);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel searchMember;
    private javax.swing.JPanel searchStaff;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
